name: Pull Requests

on:
  pull_request_target:
    types: [opened]

permissions:
  pull-requests: write

jobs:
  uneditable:
    uses: laravel/.github/.github/workflows/pull-requests.yml@main
# Update PR 05/25/2026 16:07:24
# Update PR 05/25/2026 16:07:45
